//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public int Id { get; set; }
        public string EduSystem { get; set; }
        public string Education { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public string School { get; set; }
        public int Pid { get; set; }
    }
}
