//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        public int Id { get; set; }
        public Nullable<int> Flag { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Department { get; set; }
        public string Company { get; set; }
        public string Nation { get; set; }
        public string Sex { get; set; }
        public string Card { get; set; }

        public List<Info> List { get; set; }
    }
}
